# main text of home
name: Miquel Mariano
#bio: Consultor TI en Ncora | VCP5/6-DCV | vExpert   Apasionado de la montaña | Bike | Trail | Run | Padre de Aina
bio1: Consultor TI en Ncora 
bio2: VCAP6-DCV Deploy | VCP5/6-DCV | vExpert x3
bio3: Apasionado de la montaña | Bike | Trail | Run
bio4: Padre de Aina ♥

# twitter summary info
description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg
images: assets/images/
vcap_images: https://miquelMariano.github.io/assets/images/vcap
imagesposts2016: https://miquelMariano.github.io/assets/images/posts/2016
imagesposts2017: https://miquelMariano.github.io/assets/images/posts/2017
imagesposts2018: https://miquelMariano.github.io/assets/images/posts/2018

# If you want to include your resume, set to true
# and specify source (external or local).
#resume: true
#resume-external: true
#resume-url: https://google.com/?q=my+resume

url: https://miquelMariano.github.io
# your url: http://USERNAME.github.io

permalink: /:year/:month/:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-89683320-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: miquelmariano # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: miquelMariano
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: miquelMariano
youtube: ncoratv
# spotify: myspotify
github: miquelMariano
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
email: miquel.mariano@outlook.com

authors:
    miquelMariano:
        name: Miquel Mariano
        bio: DevOps at Ncora | VCAP6-DCV Deploy | VCP5/6-DCV | vExpert x3
        external-image: false
        picture: assets/images/profile.jpg
        twitter: miquelMariano
#    jamesfoster:
#        name: James Foster
#        bio: A Man who develops software with coffee
#        external-image: false
#        picture: assets/images/james.jpg
#        twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
paginate: 15
paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
#projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# add new buttons
galaxy: true


# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
